export { default as Header } from './Header'
export { default as QualityFeatureOne } from './QualityFeatureOne'
export { default as CoreFeaturesOne } from './CoreFeaturesOne'
export { default as QualityFeatureTwo } from './QualityFeatureTwo'
export { default as CoreFeaturesTwo } from './CoreFeaturesTwo'
export { default as FunctionOne } from './FunctionOne'
export { default as Testimonial } from './Testimonial'